[project]
name = "movie-information-extractor"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Robel Gebregziabher", email = "robelgher16@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "accelerate>=1.14.0",
    "langchain>=1.4.0",
    "langchain-core>=1.6.2",
    "langchain-google-genai>=4.4.0",
    "langchain-huggingface>=1.2.2",
    "pydantic>=2.13.5",
    "python-dotenv>=1.2.3",
    "streamlit>=1.63.0",
    "torch>=2.14.0",
    "transformers>=5.16.1",
]

[project.scripts]
movie-information-extractor = "movie_information_extractor:main"

[build-system]
requires = ["uv_build>=0.12.11,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
